---
# Variable setup.
- name: Include version-specific variables for Redhat/Centos.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Debian'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Ubuntu'

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
# - include_tasks: setup-FreeBSD.yml
#   when: ansible_os_family == 'FreeBSD'

# - include_tasks: setup-OpenBSD.yml
#   when: ansible_os_family == 'OpenBSD'

# - include_tasks: setup-Archlinux.yml
#   when: ansible_os_family == 'Archlinux'

# Vhost configuration.
- import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ nginx_root_group }}"
    force: true
    lstrip_blocks: true
    mode: 0644

- name: Ensure {{ service_name }} service is running as configured.
  service:
    name: "{{ service_name }}"
    state: "{{ service_service_state }}"
    enabled: "{{ service_service_enabled }}"
  changed_when: false
